apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: uru0miicy-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/uru0miicy-java-springboot-gitops